spring:
  application:
    name: resource-api

  datasource:
    url: jdbc:postgresql://localhost:5432/neondb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth.neonteam.ir/realms/interview

server:
  port: 8080
springdoc:
  swagger-ui:
    path: /swagger-ui

  api-docs:
    path: /api-docs